--Default values

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;

INSERT INTO CONVERSION
(SOURCE_AMOUNT, SOURCE_CURRENCY,TARGET_AMOUNT, TARGET_CURRENCY, TRANSACTION_DATE)
VALUES
(1,  'EUR', 1, 'TRY', '2020-10-03')
;
